name = "VelonaSMP 2024"
author = "IONNetwork, Yi_annick, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e08a567c9426a8aadae2cd0c65895ce10fedb7ba518177ef33d61716ff7ff4be"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
